set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "SequoiaDB")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
if(PROJECT_VERSION_PATCH)
   set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
   set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
else()
   set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")
endif()

if(ENTERPRISE)
   SET(PACKAGE_NAME
       "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}_${CMAKE_HOST_SYSTEM_PROCESSOR}-enterprise-bin")
else()
   SET(PACKAGE_NAME
       "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}_${CMAKE_HOST_SYSTEM_PROCESSOR}-bin")
endif()

# Use lower case in the package name
string(TOLOWER ${PACKAGE_NAME} CPACK_PACKAGE_FILE_NAME)

if(PACK_TEST)    
  add_custom_target(buildpackage
      COMMAND bash -c "tar zcvf ${PACKAGE_NAME}.tar.gz *"
      COMMAND bash -c " mv ${PACKAGE_NAME}.tar.gz ${CMAKE_SOURCE_DIR}/build"
      WORKING_DIRECTORY "${CMAKE_INSTALL_PREFIX}"
      DEPENDS ${CMAKE_INSTALL_PREFIX}
      COMMENT "build package..."
      )
else()
  add_custom_target(buildpackage
      COMMAND bash -c "rm -rf mysql-test"
      COMMAND bash -c "tar zcvf ${PACKAGE_NAME}.tar.gz *"
      COMMAND bash -c " mv ${PACKAGE_NAME}.tar.gz ${CMAKE_SOURCE_DIR}/build"
      WORKING_DIRECTORY "${CMAKE_INSTALL_PREFIX}"
      DEPENDS ${CMAKE_INSTALL_PREFIX}
      COMMENT "build package..."
      )
endif()

set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_GENERATOR "TGZ")

include(CPack)
